# Conda environment specification. The dependencies defined in this file will
# be automatically provisioned for managed runs. These include runs against
# the localdocker, remotedocker, and cluster compute targets.

# Note that this file is NOT used to automatically manage dependencies for the
# local compute target. To provision these dependencies locally, run:
# conda env update --file conda_dependencies.yml

# Details about the Conda environment file format:
# https://conda.io/docs/using/envs.html#create-environment-file-by-hand

# For managing Spark packages and configuration, see spark_dependencies.yml.
# Version of this configuration file's structure and semantics in AzureML.
# This directive is stored in a comment to preserve the Conda file structure.
# [AzureMlVersion] = 2

name: yolov5_training_env
dependencies:
  # The python interpreter version.
  # Currently Azure ML Workbench only supports 3.5.2 and later.
  - python=3.7.*
  - pip

  - pip:
      # Base AzureML SDK
      - azureml-sdk==1.43.*

      # Must match AzureML SDK version.
      # https://docs.microsoft.com/en-us/azure/machine-learning/concept-environments
      - azureml-defaults==1.43.*

      # Training deps
      - matplotlib>=3.2.2
      - numpy>=1.18.5
      - opencv-python>=4.1.1
      - Pillow>=7.1.2
      - PyYAML>=5.3.1
      - requests>=2.23.0
      - scipy>=1.4.1
      - torch>=1.7.0  # see https://pytorch.org/get-started/locally/ (recommended)
      - torchvision>=0.8.1
      - tqdm>=4.64.0
      - tensorboard>=2.4.1
      - pandas>=1.1.4
      - seaborn>=0.11.0
      # - gunicorn>=20.1.0
      - python-dotenv==0.12.0

      # Scoring deps
