$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: yolov5-1
endpoint_name: yolov5-mlops
model: azureml:yolov5_model.pt:1
code_configuration:
  code: ./scoring
  scoring_script: score.py
environment:
  conda_file: ./conda_dependencies.yml
  image: mcr.microsoft.com/azureml/openmpi3.1.2-ubuntu18.04:20210727.v1
instance_type: Standard_DS1_v2 
instance_count: 1
